### ISSUE TITLE
Which extension is the correct one?

### ISSUE THREAD

**Issue by piegamesde** [pbxqdown/gnome-shell-extension-transparent-window#12]
There are two extensions that point to that source code:

- https://extensions.gnome.org/extension/1454/transparent-window/
- https://extensions.gnome.org/extension/4016/transparent-window/

Which one is the correct one to use? Who maintains them?

**Comment by pbxqdown** [comment]
Thanks for the hint. I develop this extension with https://extensions.gnome.org/extension/1454/transparent-window/ . I don't know why it is forked by https://extensions.gnome.org/extension/4016/transparent-window/

**Comment by piegamesde** [comment]
Thank you. I don't know about the other one, or about the duplication policy of extensions.gnome.org.

**Comment by pbxqdown** [comment]
Yeah, although gnome extensions are all open sourced, having a totally copied product uploaded feels piracy.. But looks like it still points to this github repo, and i didn't even find out a place to report this type of incident on Gnome website...
Thanks again for finding this issue.
