### ISSUE TITLE
Save settings?

### ISSUE THREAD

**Issue by JouBqa** [pbxqdown/gnome-shell-extension-transparent-window#14]
Is there a way to save the setting for a window type? For examply I have to set the transparency for every Nautilus window I open, it would be nice if they all had the same transparency automatically

**Comment by pbxqdown** [comment]
See #7. This feature seems to be another type of window transparency application. Since transparency-by-window-type is quite static, i would recommend using shell scripts(e.g. xprop command) running at OS startup to achieve similar effect.
