### ISSUE TITLE
The extension is incompatible with the current GNOME version 42.1

### ISSUE THREAD

**Issue by rogue-agent** [pbxqdown/gnome-shell-extension-transparent-window#17]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: SK Arch Linux 0.4.1
- **GNOME version**: 42.1
- **Display Server(X11/Wayland)**: Wayland
- **Exact command to reproduce**: Manually install

You can obtain the GNOME version by:
1. Open the Activities overview and start typing About.
2. Click on About to open the panel. A window appears showing information about your system, including your distribution's name and the GNOME version.

### Describe the problem
Downloaded from extensions page(latest) (latest) and manually installed

### Source code / logs 
```
`Error: No property margin on GtkBox

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
  _init@/home/wz/.local/share/gnome-shell/extensions/transparent-window@pbxqdown.github.com/prefs.js:62:26
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  buildPrefsWidget@/home/wz/.local/share/gnome-shell/extensions/transparent-window@pbxqdown.github.com/prefs.js:98:16
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  `
```

**Comment by pbxqdown** [comment]
It seems that the issue is due to GTK4 deprecated margin property with margin-*(e.g. margin-top, margin-bottom) instead. Articles:
https://docs.gtk.org/gtk4/migrating-3to4.html
https://discourse.gnome.org/t/why-did-margin-property-disappeared-in-gtk4/5530
I don't have Gnome 42 environment, could you manually modify prefs.js containing margin keyword and and see whether it works? Thanks.

**Comment by igolskyi** [comment]
Thank you @pbxqdown for the suggestion, I changed "margin" to "margin-start" for example. But I got the following error:
```
TypeError: ModifierKeyLabel.set_line_wrap is not a function

Stack trace:
  _init@/home/igolskyi/.local/share/gnome-shell/extensions/transparent-window@pbxqdown.github.com/prefs.js:64:22
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  buildPrefsWidget@/home/igolskyi/.local/share/gnome-shell/extensions/transparent-window@pbxqdown.github.com/prefs.js:98:16
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
Unfortunately, it seems that this will also not be the last mistake.

**Comment by pbxqdown** [comment]
Thanks @igolskyi for helping with this. It seems that gtk4 renames set_line_wrap with set_wrap, maybe you can try and see whether it fixes the issue? 
https://docs.gtk.org/gtk4/method.Label.set_wrap.html

**Comment by igolskyi** [comment]
Yes, I renamed set_line_wrap with set_wrap.

Next error:
```
TypeError: ModifierKeyBox.pack_start is not a function

Stack trace:
  _init@/home/igolskyi/.local/share/gnome-shell/extensions/transparent-window@pbxqdown.github.com/prefs.js:74:20
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  buildPrefsWidget@/home/igolskyi/.local/share/gnome-shell/extensions/transparent-window@pbxqdown.github.com/prefs.js:98:16
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by pbxqdown** [comment]
maybe try ModifierKeyBox.box_prepend, or ModifierKeyBox.prepend?

**Comment by igolskyi** [comment]
So prepend worked.
Next error: `TypeError: ModifierKeyBox.add is not a function`

**Comment by pbxqdown** [comment]
gosh gtk4 changes everything😂
maybe try ModifierKeyBox.append? the definition is in: https://docs.gtk.org/gtk4/class.Box.html

**Comment by igolskyi** [comment]
So I replaced .add() with .append()

Next, I commented this line: 
```
// widget.show_all();
```
Because:
 ```
The function gtk_widget_show_all(), the GtkWidget:no-show-all property, and its getter and setter have been removed in GTK 4, so you should stop using them.
```
And finally no more mistakes :)

![image](https://user-images.githubusercontent.com/22115961/170885193-19dfa475-a3c9-4ddd-9f7c-d44ea1a20d14.png)

**Comment by igolskyi** [comment]
All changes:
```
margin --> "margin-start"
set_line_wrap() --> set_wrap()
pack_start() --> prepend()
add() --> append()

// widget.show_all();
```

**Comment by pbxqdown** [comment]
Thanks @igolskyi This is awesome! 
I saw that GTK4 is included since Gnome40: https://help.gnome.org/misc/release-notes/40.0/developers.html.en
so maybe this will fix all Gnome40 upwards version?

**Comment by igolskyi** [comment]
Most likely yes, but we need more feedback on other versions of Gnome40.

**Comment by pbxqdown** [comment]
Since I haven't upgraded since gnome 3.36 yet, i'm not able to verify.. Please let me know if the extension works on Gnome40 if you have used it.
There is a version control feature of the extension: https://github.com/pbxqdown/gnome-shell-extension-transparent-window/blob/239529a38dc6aeb5c645c0692b9cf1e52b7c0a4e/extension.js#L112
maybe we can define a gnome_at_least_40_1 variable to make it compatible with both GNOME3X and Gnome 4X

**Comment by igolskyi** [comment]
All changes I've tested for GNOME Shell 42.0:
```
let gnome_at_least_40_1;
...
...
function init() {
  ...
  ...
  gnome_at_least_3_38 = isVersionGreaterOrEqual(3, 38);
  gnome_at_least_40_1 = isVersionGreaterOrEqual(40, 1);
}
...
...
if (gnome_at_least_40_1) {
```

After restart's `Alt+F2   r` extension still works.

**Comment by pbxqdown** [comment]
Nice! Could you submit a MR for this? It seems that there is no version check for prefs.js yet

**Comment by igolskyi** [comment]
Good idea. Could you please review for https://github.com/pbxqdown/gnome-shell-extension-transparent-window/pull/18

**Comment by pbxqdown** [comment]
> Good idea. Could you please review for #18
> 
> P.S. //TODO:support multi-monitor https://github.com/pbxqdown/gnome-shell-extension-transparent-window/blob/master/extension.js#L117 would be amazing ;)

Yep, i think it is doable, but the GTK API is ever-changing and hard to find reference😂

**Comment by igolskyi** [comment]
@rogue-agent could you please check if the new version works?

**Comment by rogue-agent** [comment]
![image](https://user-images.githubusercontent.com/9405663/171447336-b25ccbc0-0dc3-4265-ad1f-326187293a4f.png)
![image](https://user-images.githubusercontent.com/9405663/171447453-5bf93f86-08cc-4a58-8a8c-feaffd47c36b.png)

**Comment by rogue-agent** [comment]
Disabled all other window decorations, extensions and themes.

**Comment by pbxqdown** [comment]
@rogue-agent try change log verbose level to "Debug" and `sudo journalctl -f /usr/bin/gnome-shell` may print more debug details

**Comment by rogue-agent** [comment]
![image](https://user-images.githubusercontent.com/9405663/171462399-82f1cb68-13be-484e-9044-12995816068e.png)
It recognizes me pressing Ctrl + V and other button combinations.

**Comment by pbxqdown** [comment]
Yes so the hotkey detection works. I saw your hotkey code is set to 14. I think you are not pressing the correct hotkey?

**Comment by rogue-agent** [comment]
Is this hotkey activated? I thought this was basic transparency like in Windows. What hotkey combination?

**Comment by rogue-agent** [comment]
I pressed them in order you wrote. I don't know what there is control and shift if there is Control and Shift for left and right in the end.
![image](https://user-images.githubusercontent.com/9405663/171473433-4d0717fc-627b-4ad0-bced-9246e5baf28a.png)

**Comment by pbxqdown** [comment]
if you want ctrl+shift, the modifier key would be 1+4 which is 5. You can then set 5 as the keycode and hover on a window, press ctrl+shift and scroll the mouse wheel

**Comment by rogue-agent** [comment]
I don't know. I set it to 18 for AltGr+ShiftL, I'm on a laptop so I used two finger scroll.

**Comment by pbxqdown** [comment]
maybe try default setting with Alt key(code is 8)? Under normal condition there would be logs of:
` [DEBUG][TransparentWindow] Modifier key pressed, listening to scroll`

**Comment by igolskyi** [comment]
Hm... In my case https://github.com/pbxqdown/gnome-shell-extension-transparent-window/issues/17#issuecomment-1140498627   the key code of `left Alt` is **24**

**Comment by pbxqdown** [comment]
@igolskyi  Yep guess different regions have different keyboard layout/code.
 @rogue-agent  Awesome so we can verify the extension work on Gnome42.

**Comment by igolskyi** [comment]
@pbxqdown also, check if nothing is broken on older versions.

**Comment by pbxqdown** [comment]
Yes, the extension works on my GNOME 3.36. And older version's code keeps untouched.

**Comment by pbxqdown** [comment]
@igolskyi I suddenly have an idea why your Alt key code is 24. Do you have a keyboard with numlock? Since numlock's keycode is 16, 16(NUMSlock)+8(ALT) would get 24.
This PR may mask off numlock key: https://github.com/pbxqdown/gnome-shell-extension-transparent-window/pull/19

**Comment by igolskyi** [comment]
@pbxqdown  Yes, my laptop with numlock :)
