### ISSUE TITLE
Not work for some windows under wayland

### ISSUE THREAD

**Issue by OmmyZhang** [pbxqdown/gnome-shell-extension-transparent-window#21]
### System information
- **OS Platform and Distribution:** linux Arch
- **GNOME version**: 42.2
- **Display Server(X11/Wayland)**: Wayland
- **Exact command to reproduce**:

### Describe the problem
It works fine when using Xorg(with `WaylandEnable=false`), but when using Wayland, some windows work, some not.
For example, Chrome works, gnome-terminal not.

### Source code / logs 
No any debug log when trying to scroll on windows that do not work, and normal logs for those work fine.

**Comment by pbxqdown** [comment]
Thanks for reporting the issue! It seems that some users reported similar issue before. 

The main logic of the extension is: press hotkey -> create an overlay -> detect scroll event from this overlay -> change transparency based on scroll event.

Are you able to see the log such as ```[DEBUG][TransparentWindow] Hot key pressed```? If there is such log, we can confirm hotkey detection works fine.

**Comment by OmmyZhang** [comment]
For the windows that work, yes there're such logs.

```
$ journalctl /usr/bin/gnome-shell -f
...
...
Jun 23 14:54:53 D gnome-shell[1121]: [DEBUG][TransparentWindow] Hot key pressed
Jun 23 14:54:53 D gnome-shell[1121]: [DEBUG][TransparentWindow] 8
Jun 23 14:54:53 D gnome-shell[1121]: [DEBUG][TransparentWindow] Modifier key pressed, listening to scroll
Jun 23 14:54:53 D gnome-shell[1121]: [DEBUG][TransparentWindow] overlay created
Jun 23 14:54:53 D gnome-shell[1121]: [DEBUG][TransparentWindow] Hot key pressed
Jun 23 14:54:53 D gnome-shell[1121]: [DEBUG][TransparentWindow] 0
Jun 23 14:54:53 D gnome-shell[1121]: [DEBUG][TransparentWindow] overlay destroyed
```

But for those not work, just nothing. No any log appears after I press alt.

**Comment by pbxqdown** [comment]
The hotkey logic is defined in a per-display way: https://github.com/pbxqdown/gnome-shell-extension-transparent-window/blob/cc9bc70c192dd565fa6f1d1b28d9a20f99684f2a/extension.js#L161
I'm not sure whether it is possible that wayland uses different displays for different windows.

Could you list all window types that don't work? This may give us some hint.
Also please check whether it is possible the hotkey is masked by application's shortcut key.

**Comment by OmmyZhang** [comment]
Not work: gnome-terminal, Files, Settings(and all system setting windows, such as Extensions and Tweaks), gedit.

It seems only work on applications that are somehow third part, like Firefox, Chrome, VLC.

As there's no any log when I just press alt, I think this problem may not related to  application's shortcut key.

**Comment by pbxqdown** [comment]
for the gnome-terminal window, do you select/focus that window and hotkey doesn't work? how about try this: select a chrome window, press hotkey, then move cursor to hover on gnome-terminal window, then scroll and see if it changes opacity.

**Comment by OmmyZhang** [comment]
> select a chrome window, press hotkey, then move cursor to hover on gnome-terminal window, then scroll and see if it changes opacity.

Yes, this works. Terminal's opacity is changed. Amazing!

**Comment by pbxqdown** [comment]
Awesome! But still this is strange..guess gnome-terminal somewhat capture the hotkey event such that it can not be received.

**Comment by cazacugmihai** [comment]
Hi! 

I also encounter this issue when using most applications (e.g. Nautilus, Firefox, Sublime Text, Terminal, Tilix, VLC, Double Commander, etc.), but the extension works fine with Google Chrome, Chromium, and IntelliJ IDEA.

Some applications (not all) will respond correctly if I follow your advice:

> for the gnome-terminal window, do you select/focus that window and hotkey doesn't work? how about try this: select a chrome window, press hotkey, then move cursor to hover on gnome-terminal window, then scroll and see if it changes opacity.

or by running one of these two commands:

> dbus-run-session -- gnome-shell --nested --wayland

> dbus-run-session -- gnome-shell --nested

Those who don't respond correctly after trying the above workarounds are only changing the transparency of certain parts of their tile bars, especially the corners.

Here are the logs related to this extension:

> \> **journalctl /usr/bin/gnome-shell -f | grep -i "transparent.\*window"**

> Hint: You are currently not seeing messages from other users and the system.
>       Users in groups 'adm', 'systemd-journal' can see all messages.
>       Pass -q to turn off this notice.
> Jun 14 17:12:14 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] Gnome version:43.9

and the logs when using the workaround(s):

> Hint: You are currently not seeing messages from other users and the system.
>       Users in groups 'adm', 'systemd-journal' can see all messages.
>       Pass -q to turn off this notice.
> Jun 14 17:12:14 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] Gnome version:43.9
> Jun 14 17:14:31 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] Hot key pressed
> Jun 14 17:14:31 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] 8
> Jun 14 17:14:31 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] Modifier key pressed, listening to scroll
> Jun 14 17:14:31 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] overlay not created
> Jun 14 17:14:31 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] overlay created
> Jun 14 17:14:32 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] on scroll
> Jun 14 17:14:32 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] 1743,829
> Jun 14 17:14:32 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] 4
> Jun 14 17:14:32 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] on scroll
> Jun 14 17:14:32 msnb gnome-shell[2017230]: [DEBUG][TransparentWindow] 1743,829

System info:
- OS Name: Debian GNU/Linux 12 (bookworm)
- Gnome Version: 43.9
- Windowing System: Wayland

**Comment by pbxqdown** [comment]
Hi @cazacugmihai Thanks for raising the issue! Since only some window has issue, guess those windows may have special properties. Sorry the extension may not be able to cover all cases. Please try if command line tools such as xprops can help change transparency of those windows.
