### ISSUE TITLE
Incompatible with Gnome Shell 43...

### ISSUE THREAD

**Issue by salazarbarrera** [pbxqdown/gnome-shell-extension-transparent-window#22]
...but it can be fixed by adding "43" to the list of supported shell versions. It will still present the issue #15, but at least it will work without the possibility to change the shortcut via settings.

**Comment by pbxqdown** [comment]
Would you submit a patch to add "43" if you have tested it on gnome43 and verified it works.
The shortcut can be changed by manually changing keycode, but indeed pressing shortcut key doesn't work any more..

**Comment by salazarbarrera** [comment]
Yes, that's exactly what I do with dconf. And I'll do the PR, I already tested it on Sunday and today while working.

**Comment by pbxqdown** [comment]
Awesome. Closing with #23 fix
