### ISSUE TITLE
incompatible  after upgrade system ( upgraded gnome-shell  to version 44.1)

### ISSUE THREAD

**Issue by mnhunter** [pbxqdown/gnome-shell-extension-transparent-window#25]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Manjaro 23.0.0
- **GNOME version**: 44.1
- **Display Server (X11/Wayland)**: Wayland
- **Exact command to reproduce**:  incompatible  after update system 

 
You can obtain the GNOME version by:
1. Open the Activities overview and start typing About.
2. Click on About to open the panel. A window appears showing information about your system, including your distribution's name and the GNOME version.

### Describe the problem
Describe the problem here, including the steps to reproduce the problem.

extension is not work after upgrade (pamac update|upgrade).  adding "44.1" in metadata.json  did not solve the issue.

### Source code / logs 
Include any logs or source code that would be helpful to diagnose the problem.   
First, in the preference, Set the log verbose level to "Debug";  
Then you can view gnome shell extension's log via:  

```
journalctl -b0 /usr/bin/gnome-shell |grep -i transparent.*window
```
To view logs dynamically:
```
journalctl /usr/bin/gnome-shell -f |grep -i transparent.*window
```

**Comment by pbxqdown** [comment]
Hi @mnhunter does this issue only occurs on 44.1? There are usually issues coming out after GNOME upgrade. Probably caused by GNOME API changes. Please provide more details to better triage the issue.
