### ISSUE TITLE
overlay takeover

### ISSUE THREAD

**Issue by drzraf** [pbxqdown/gnome-shell-extension-transparent-window#26]
### System information
- **OS Platform and Distribution Linux Ubuntu 22.04**
- **GNOME version 42.9**
- **Display Server: Wayland**
- ~~Exact command to reproduce~~ 

### Describe the problem
In **some** situations (multiple times every hour), when switching to a virtual desktop, the overlay **takes over**:
- I can't focus any window on said virtual desktop anymore using the mouse
- I can launch the debugger "F2 > lg", but I can't even click its buttons
- mouse clicks are basically inoperative
- mouse scrolling changes transparency even though the "Alt" key isn't pressed

Also:
- It only happen if the focused window (on the virtual desktop I switch to) is of a certain kind: Eg some Firefox or GTK boxes (but never xterm/urxvt)
- As soon as I Alt-Tab (to focus another window on the same virtual desktop), the focus/window-grabbing behavior is restored
- If no other window exist on that desktop, I must create an xterm or similar (using keybinding) in order restore the correct behavior
- It's a new bug. It started happening a week or two ago.
- It switch desktops using Alt-1, Alt-2, Alt-3, ...

### Source code / logs 
```
août 02 00:12:04 acer gnome-shell[2829]: [DEBUG][TransparentWindow] Hot key pressed
août 02 00:12:04 acer gnome-shell[2829]: [DEBUG][TransparentWindow] 8
août 02 00:12:04 acer gnome-shell[2829]: [DEBUG][TransparentWindow] Modifier key pressed, listening to scroll
août 02 00:12:04 acer gnome-shell[2829]: [DEBUG][TransparentWindow] overlay created
août 02 00:12:04 acer gnome-shell[2829]: [DEBUG][TransparentWindow] Hot key pressed
août 02 00:12:04 acer gnome-shell[2829]: [DEBUG][TransparentWindow] 0
août 02 00:12:04 acer gnome-shell[2829]: [DEBUG][TransparentWindow] overlay destroyed
août 02 00:12:05 acer gnome-shell[2829]: [DEBUG][TransparentWindow] Hot key pressed
août 02 00:12:05 acer gnome-shell[2829]: [DEBUG][TransparentWindow] 8
août 02 00:12:05 acer gnome-shell[2829]: [DEBUG][TransparentWindow] Modifier key pressed, listening to scroll
août 02 00:12:05 acer gnome-shell[2829]: [DEBUG][TransparentWindow] overlay created
août 02 00:12:05 acer gnome-shell[2829]: [DEBUG][TransparentWindow] Hot key pressed
août 02 00:12:05 acer gnome-shell[2829]: [DEBUG][TransparentWindow] 0
août 02 00:12:05 acer gnome-shell[2829]: [DEBUG][TransparentWindow] overlay destroyed
août 02 00:12:07 acer gnome-shell[2829]: [DEBUG][TransparentWindow] Hot key pressed
août 02 00:12:07 acer gnome-shell[2829]: [DEBUG][TransparentWindow] 8
août 02 00:12:07 acer gnome-shell[2829]: [DEBUG][TransparentWindow] Modifier key pressed, listening to scroll
août 02 00:12:07 acer gnome-shell[2829]: [DEBUG][TransparentWindow] overlay created
août 02 00:12:07 acer gnome-shell[2829]: [DEBUG][TransparentWindow] Hot key pressed
août 02 00:12:07 acer gnome-shell[2829]: [DEBUG][TransparentWindow] 0
août 02 00:12:07 acer gnome-shell[2829]: [DEBUG][TransparentWindow] overlay destroyed
août 02 00:12:09 acer gnome-shell[2829]: [DEBUG][TransparentWindow] Hot key pressed
août 02 00:12:09 acer gnome-shell[2829]: [DEBUG][TransparentWindow] 8
août 02 00:12:09 acer gnome-shell[2829]: [DEBUG][TransparentWindow] Modifier key pressed, listening to scroll
```

Any race/conflict over the "Alt" key ?

**Comment by pbxqdown** [comment]
Hi @drzraf thanks for submitting the issue. Is virtual desktop a monitor or workspace? From the description it seems Alt key is both used in switching desktop and changing transparency.

**Comment by drzraf** [comment]
Sorry, "virtual desktop" as the _old_ name for **workspace** (I only have one monitor)
The alt key is used for many other keybindings (including switching workspaces)

**Comment by pbxqdown** [comment]
hmmm maybe using a different key combination will help? Like ctrl + shift, it can be set in settings page.

**Comment by drzraf** [comment]
Not an option for me. I hope this extension could (possibly?) make a better job an handling keyboard events or binding against Gnome keyboard subsystem?

**Comment by pbxqdown** [comment]
Gnome is not a well documented framework so sometimes hard to triage the issue.. maybe some corner case of switching workspace event handling logic.
It would be awesome if you could help root cause the problem. If it is a new bug maybe try switch to an older version to check if problem persists.
