### ISSUE TITLE
Gnome 3.36: `TypeError: Keymap is null` and `assignment to undeclared variable`

### ISSUE THREAD

**Issue by tYYGH** [pbxqdown/gnome-shell-extension-transparent-window#6]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 5.7.5-arch1-1 #1 SMP PREEMPT Mon, 22 Jun 2020 08:10:02 +0000 x86_64 GNU/Linux
- **GNOME version**: 3.36.3
- **Exact command to reproduce**: /usr/lib/gdm-wayland-session /usr/bin/gnome-session (login by GDM to Wayland)

### Describe the problem
The extension does not start. Running Alt+F2 “lg” to get the error logs shows this error:
`TypeError: Keymap is null`

### Source code / logs 
After setting the log level top “Debug”, I get that:

```
$ journalctl -b0 /usr/bin/gnome-shell -r |grep -i Transparent.window
juin 24 22:04:14 sedentaire gnome-shell[909]: JS ERROR: Extension transparent-window@pbxqdown.github.com: TypeError: Keymap is null
                                              enable@/home/yves/.local/share/gnome-shell/extensions/transparent-window@pbxqdown.github.com/extension.js:150:3
juin 24 22:04:14 sedentaire gnome-shell[909]: JS WARNING: [/home/yves/.local/share/gnome-shell/extensions/transparent-window@pbxqdown.github.com/extension.js 48]: assignment to undeclared variable gnome_at_least_3_34
juin 24 22:04:14 sedentaire gnome-shell[909]: JS WARNING: [/home/yves/.local/share/gnome-shell/extensions/transparent-window@pbxqdown.github.com/extension.js 24]: assignment to undeclared variable lis
```

**Comment by pbxqdown** [comment]
From the following docs:
https://developer.gnome.org/gdk3/stable/gdk3-Keyboard-Handling.html#gdk-keymap-get-default
Looks like the gdk_keymap_get_default method has been deprecated since version 3.22.
Maybe you can try ```const Keymap = Gdk.Keymap.gdk_keymap_get_for_display(gdk_display_get_default());``` in extension.js:line12? 
I'm using ubuntu20.04 and the new API doesn't work. Guess Archlinux uses new version of GDK which deprecates the old API.

**Comment by pbxqdown** [comment]
Looks like following code works for the new API, gdk version should be specified:
```
imports.gi.versions.Gdk = '3.0';
imports.gi.versions.Gtk = '3.0';

const Gdk = imports.gi.Gdk;
const Keymap = Gdk.Keymap.get_for_display(Gdk.Display.get_default());
```
Please try and see whether it works for you?

**Comment by tYYGH** [comment]
Hi @pbxqdown, thank you for looking at this issue!
With the change you suggest, I get:

```
JS ERROR: Extension transparent-window@pbxqdown.github.com: Error: Argument 'display' (type interface) may not be null
@/home/yves/.local/share/gnome-shell/extensions/transparent-window@pbxqdown.github.com/extension.js:5:27
```

with lines 1-to-20 being:

```javascript
  1 imports.gi.versions.Gdk = '3.0';                                                                                                                                                           
  2 imports.gi.versions.Gtk = '3.0';
  3 
  4 const Gdk = imports.gi.Gdk;
  5 const Keymap = Gdk.Keymap.get_for_display(Gdk.Display.get_default());
  6 
  7 const St = imports.gi.St;
  8 const Main = imports.ui.main;
  9 const Tweener = imports.ui.tweener;
 10 const Shell = imports.gi.Shell;
 11 const ExtensionUtils = imports.misc.extensionUtils;
 12 const Me = ExtensionUtils.getCurrentExtension();
 13 const Meta = imports.gi.Meta;
 14 const Clutter = imports.gi.Clutter;
 15 const Layout = imports.ui.layout;
 16 
 17 //const Gdk = imports.gi.Gdk;
 18 //const Keymap = Gdk.Keymap.get_default();
 19 
 20 //logger
```

**Comment by pbxqdown** [comment]
Sure no problem. Looks like on your machine Display.get_default() returns null. On my machine it will return: [object instance wrapper GType:GdkX11Display jsobj@0xff8d090bb0 native@0x564468d440d0]. Maybe you have multiple Xdisplay and no default display is set?
Try: ```echo $DISPLAY``` to see your current display.
```xdpyinfo``` will show more X server info.

**Comment by pbxqdown** [comment]
I tried ubuntu on Wayland myself and experienced the same issue. Looks like Wayland is just not maturely supported currently by GTK3/GNOME(i can't use guake anymore, and even "Alt+F2 + r" to restart gnome-shell is not available now...). 
This doc(https://developer.gnome.org/gdk3/stable/GdkDisplay.html   ) also states that:
 > GdkDisplay objects are the GDK representation of an **X Display**

We may have to wait long time before both GNOME/GTK framework and ecosystem fully support Wayland.

**Comment by tYYGH** [comment]
Indeed, I am using Wayland, which is Archlinux’ default for Gnome.

**Comment by pbxqdown** [comment]
I think Wayland/X11 can be selected on GNOME login screen. If X11 is available on Archlinux, maybe you can give it a try.

**Comment by tYYGH** [comment]
I can confirm: when using “Gnome on Xorg”, the extension works; when using plain “Gnome”, it does not.

**Comment by pbxqdown** [comment]
Thanks for the verification! So basically this is a Wayland/GTK3 compatibility issue.
i think the proper way to handle this issue is to wait until GNOME/GTK has a better support for Wayland. Looks like GDK4 has a display-server-neutral implementation of GdkDisplay(https://developer.gnome.org/gdk4/stable/GdkDisplay.html). We can wait until GNOME ships with GTK4.

**Comment by tYYGH** [comment]
Good point. Thanks for having had a look :-)

**Comment by pbxqdown** [comment]
You are welcome! Any idea of improvement is appreciated.

**Comment by pbxqdown** [comment]
#16 should fix this issue. Please try latest version of the extension when you get a chance.
