### ISSUE TITLE
Incompatible with 3.38 desktop

### ISSUE THREAD

**Issue by coadmunkee** [pbxqdown/gnome-shell-extension-transparent-window#8]
The tweener library has been moved from imports.ui.tweener to imports.tweener.tweener. However after fixing the local reference I am able to load the extension, but it seems that even with this fix the extension is no longer able to capture the scroll actions to change transparency levels. Unfortunately, I am not skilled enough to capture any better troubleshooting information.

**Comment by coadmunkee** [comment]
after further poking around I've found one more change that needs to be made for 3.38 compatibility. In extension.js, there is call at [line 107 of createOverlay](https://github.com/pbxqdown/gnome-shell-extension-transparent-window/blob/177f7886c0495ba25c44c1134aca8e46455c7fd8/extension.js#L103) where overlay new St.Bin() is called with parameters that have been deprecated. Replacing x_fill with x_expand and replacing y_fill with y_expand fixes the issue.

**Comment by pbxqdown** [comment]
Thanks for helping with this issue! Change has been merged.
